services:

  carla-simulator:
    deploy:
      resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: /.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/.Xauthority:ro
    privileged: True
    image: carla-health # TODO: Change to rwthika/carla-simulator:server
    command: bash -ic './CarlaUE4.sh -nosound $SIMULATOR_FLAGS 2>/dev/null'

  carla-scenario-runner:
    depends_on:
      carla-simulator:
        condition: service_healthy
    volumes:
      - $SCENARIO_DIRECTORY:/scenarios
    image: rwthika/carla-scenario-runner:latest
    command: bash -ic "python ./scenario_runner.py --host carla-simulator --openscenario /scenarios/$SCENARIO_NAME --output"
