name: automated-testing
on: push
jobs:
  generate-scenario-job-matrix:
    runs-on: self-hosted
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    name: generate scenario job matrix
    steps:
      - uses: actions/checkout@v4
      - id: generate
        uses: ./.github/actions/generate-matrix
        with:
          starting-point: ./utils/scenarios
          query-string: '*.xosc'
          exclude-string: '*/catalogs/*'

  evaluate-required-scenarios:
    needs: generate-scenario-job-matrix
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-scenario-job-matrix.outputs.matrix) }}
    name: Eval ${{ matrix.filename }}
    steps:
      - run: rm -rf *
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run-scenario
        with:
          scenario-folder-path: ${{ matrix.filedir }}
          scenario-file-name: ${{ matrix.filename }}
          simulator-image: carla-health # TODO: Change to rwthika/carla:server
          simulator-offscreen: false

  generate-opt-scenario-job-matrix:
    runs-on: self-hosted
    outputs:
      opt-matrix: ${{ steps.generate-opt.outputs.matrix }}
    name: generate optional scenario job matrix
    steps:
      - uses: actions/checkout@v4
      - id: generate-opt
        uses: ./.github/actions/generate-matrix
        with:
          starting-point: ./utils/scenarios
          query-string: '*.xosc.opt'
          exclude-string: '*/catalogs/*'

  evaluate-required-scenarios:
    needs: generate-opt-scenario-job-matrix
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-opt-scenario-job-matrix.outputs.opt-matrix) }}
    name: Eval ${{ matrix.filename }}
    steps:
      - run: rm -rf *
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run-scenario
        continue-on-error: true
        with:
          scenario-folder-path: ${{ matrix.filedir }}
          scenario-file-name: ${{ matrix.filename }}
          simulator-image: carla-health # TODO: Change to rwthika/carla:server
          simulator-offscreen: false
