name: testing-workflow
on: push
jobs:
  testjob:
    runs-on: [self-hosted, i2100038]
    name: testjob
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy-environment
        with:
          remote-repository: BenediktHaas96/testing
          remote-deploytoken: ${{ secrets.SSH_WRONGKEY }}
          remote-composefile: "myfolder/myfile.yml"
