name: testing-workflow
on: push
jobs:
  testjob:
    runs-on: [self-hosted, i2100038]
    name: testjob
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy-environment
        with:
          composefile-path: temp-composefile.yml
          remote-repository: BenediktHaas96/testing
          remote-deploytoken: ${{ secrets.SSH_PRIVKEY }}
          remote-composefile: "myfolder/myfile.yml"
          remote-path: ./deploy-env
      - uses: actions/download-artifact@v4
        with:
          name: rendered-composefile
      - shell: bash
        run: cat temp-composefile.yml
