name: testing-workflow
on: push
jobs:
  # deploy-environment:
  #   runs-on: [self-hosted, i2100038]
  #   name: deploy environment
  #   steps:
  #     - uses: actions/checkout@v4
  #     - shell: bash
  #       run: |
  #             xhost +local:
  #     - uses: ./.github/actions/deploy-environment
  #       with:
  #         composefile-path: temp-composefile.yml
  #         remote-repository: BenediktHaas96/testing
  #         remote-deploytoken: ${{ secrets.SSH_PRIVKEY }}
  #         remote-composefile: "myfolder/myfile.yml"
  #         remote-path: ./deploy-env/
  
  generate-scenario-job-matrix:
    # needs: deploy-environment
    runs-on: [self-hosted, i2100038]
    name: Generate scenario job matrix
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: generate
        uses: ./.github/actions/generate-job-matrix
        with:
          starting-point: ./tmpfolder
          query-string: '*.xosc'
          exclude-string: '*/catalogs/*'

  simulation-scenario-tests:
    needs: generate-scenario-job-matrix
    runs-on: [self-hosted, i2100038]
    name: Evaluate ${{ matrix.filename }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-scenario-job-matrix.outputs.matrix) }}
    steps:
      - shell: bash
        run: |
              xhost +local:
      - uses: BenediktHaas96/carlos-simulation-test@v0.1.2 #./.github/composite/simulation-testing
        with:
          composefile-path: temp-composefile.yml
          remote-repository: BenediktHaas96/testing
          remote-deploytoken: ${{ secrets.SSH_PRIVKEY }}
          remote-composefile: "myfolder/myfile.yml"
          scenario-folder-path: ${{ matrix.filedir }}
          scenario-file-name: ${{ matrix.filename }}
          carla-hostname: carla-simulator
          docker-network: tempcompose_default
      - shell: bash
        run: |
              xhost -local:

  # run-scenarios:
  #   needs: generate-scenario-job-matrix
  #   runs-on: [self-hosted, i2100038]
  #   name: Run ${{ matrix.filename }}
  #   strategy:
  #     fail-fast: false
  #     matrix: ${{ fromJson(needs.generate-scenario-job-matrix.outputs.matrix) }}
  #   steps:
  #     - uses: ./.github/actions/run-scenario
  #       with:
  #         scenario-folder-path: ${{ matrix.filedir }}
  #         scenario-file-name: ${{ matrix.filename }}
  #         carla-hostname: carla-simulator
  #         docker-network: tempcompose_default

  # destroy-environment:
  #   needs: run-scenarios
  #   if: ${{ always() && !cancelled() }}
  #   runs-on: [self-hosted, i2100038]
  #   name: destroy environment
  #   steps:
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: rendered-composefile
  #     - shell: bash
  #       run: |
  #             docker compose -f temp-composefile.yml kill
  #             docker compose -f temp-composefile.yml down
  #             xhost -local:
